src/PageControls.tsx

Issue 18: Hide Fuel Switching Projects

---

src/trackedStats.tsx

Issue 17: Fix NG Gauge

---

src/components/Dashboard.tsx

Issue 32: Rearrange labels at the top

---

.eslintrc.yml
src/App.tsx
src/Projects.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

Issue 15: back button

---

.eslintrc.yml
src/Projects.tsx

#24 
- Updating eslint vals to warn also

Change waste-heat-recovery ng reduction from 50k to 250

---

.eslintrc.yml
src/App.tsx
src/Projects.tsx
src/components/YearRecap.tsx

#15 
- This take's Rachel's issue-15 branch and changes data structure to use CompletedProject object array

Issue 15 - use CompletedProject object array instead of nested arrays

---

src/App.tsx

Issue 33: End of each period - check if won

---

src/App.tsx
src/PageControls.tsx

Issue 16: Add a Start Over button

---

.eslintrc.yml
README.md
src/PageControls.tsx
src/Projects.tsx
src/components/Buttons.tsx
src/components/GroupedChoices.tsx

#21 
- Bigger header font, left align text content
- Add choiceStat for energy savings in header

Issue 21 - Update to project choice card layouts

---

src/App.scss
src/App.tsx
src/PageControls.tsx
src/Projects.tsx
src/components/Buttons.tsx
src/components/CompareDialog.tsx
src/components/GroupedChoices.tsx
src/components/InfoDialog.tsx
src/components/YearRecap.tsx
src/components/controls.tsx
src/functions-and-types.tsx

#25 
Some changes showing up in here for a previous merge - sorry about that.
- Allows user compare 2-3 projects at once. 
- Auto-opens comparison after 3 selected
- Deselects project comparison if implemented
- Leaving some comments tagged 'todo 25' for a couple later nice to haves or room for changes

Issue 25 - Add project comparison

---

.eslintrc.yml
src/Projects.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx

#60 
- Use single/no decimal place, and currency formatting
- changing some eslint styles that shouldn't break build

Issue 60 - Fixes to number formatting

---

src/App.tsx

Issue 66 -  Set scroll state only when dialogs are closing

---

.eslintrc.yml
src/App.tsx
src/PageControls.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

Issue 72 - Add results, fix carbon savings calculation

---

.eslintrc.yml
src/App.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx

Issue 68 - Progress Bar Styling

---

src/Projects.tsx

Issue 23 - Limit projects by budget period

---

src/App.tsx
src/PageControls.tsx
src/components/GroupedChoices.tsx
src/components/ScopeTabs.tsx

Issue 14: Add tabs to toggle between scope 1 and 2

---

src/components/YearRecap.tsx

Issue 76: Year Recap improvements/clean up

---

src/App.scss
src/components/SelectGameSettings.tsx

Issue 90: "Settings" Page update

---

src/Projects.tsx
src/components/YearRecap.tsx

Issue 23, 72 - Add EOY stats, fix project limits

---

src/PageControls.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

Issues 80 & 85

---

src/App.tsx
src/PageControls.tsx
src/Projects.tsx
src/components/YearRecap.tsx

#88 
Keeping some logging in for future debugging with Kristina
- Add ability to have projects with single time period implementation savings (solar carport), that then reveal maintenance or dependant projects

Issue 88 - Solar carport with Maintenance project

---

src/Projects.tsx

Issue 86 Info Stat cards need units

---

src/App.tsx
src/Projects.tsx
src/components/YearRecap.tsx

Issue 99 - Fix compare dialog, last year next button, total money spent

---

src/Projects.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

Issue 96 - Fix project costs, limits, cost per carbon

---

src/App.tsx
src/Projects.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

issue 127 added Hydrogen as fuel

---

src/PageControls.tsx
src/Pages.tsx
src/Projects.tsx

added hydrogen test project

---

src/components/Dashboard.tsx
src/components/theme.tsx

Issue 131: Clean up UI on select projects page

---

src/components/YearRecap.tsx
src/components/YearRecapCharts.tsx

Issue 130: Year Recap graph responsiveness and error

---

src/App.scss
src/App.tsx
src/PageControls.tsx
src/Projects.tsx
src/components/Buttons.tsx
src/components/CurrentPage.tsx
src/components/Dashboard.tsx
src/components/GroupedChoices.tsx
src/components/SelectGameSettings.tsx
src/components/YearRecap.tsx
src/components/YearRecapCharts.tsx
src/trackedStats.tsx

Most notable changes are in YearRecap and trackedStats renaming. Keeping all comments, because there are some weird workarounds we did last year that need to be known...

Issue 140 - Improve dev experience 

---

.github/workflows/main.yml
.github/workflows/web.yml
package.json

- Updated package.json to add in nodejs and npm engine versions
- Added building and deployment pipeline for web
Note: The node version is dynamically set by pulling it from package.json, so if upgrading node for the project, the pipeline does not need to be changed, only the version of node set in package.json.

Automate building and deployment process

---

src/PageControls.tsx
src/Projects.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

issue 135: Replace 'Carbon Savings' with 'GHG Reduction'

---

src/App.scss
src/App.tsx
src/Projects.tsx
src/components/CurrentPage.tsx
src/components/SelectGameSettings.tsx

#150 
Leaving start year options at 5 for now

Issue 150 - Add financing start year

---

.eslintrc.yml
tsconfig.json

#146 
- Turning off rules that are counter to most of the practices in MEASUR/VERIFI - making dev take longer for only minor stylistic benefit
- Strict mode off

More Eslint changes

---

src/App.scss
src/App.tsx
src/Projects.tsx
src/capitalFunding.tsx
src/components/CurrentPage.tsx
src/components/Dashboard.tsx
src/components/YearRecap.tsx
src/trackedStats.tsx

#146 
leaving a little console logging in

Issue 146 - Display Capital Funding rewards at year recap

---

.eslintrc.yml
src/App.scss
src/App.tsx
src/PageControls.tsx
src/ProjectControl.tsx
src/Projects.tsx
src/capitalFunding.tsx
src/components/Buttons.tsx
src/components/CurrentPage.tsx
src/components/Dashboard.tsx
src/components/Dialogs/CompareDialog.tsx
src/components/Dialogs/InfoDialog.tsx
src/components/Dialogs/ProjectDialog.tsx
src/components/Dialogs/dialog-functions-and-types.tsx
src/components/GroupedChoices.tsx
src/components/SelectGameSettings.tsx
src/components/StartPage.tsx
src/components/YearRecap.tsx
src/components/controls.tsx

#160 
Also breaking up projects and project controls. some minor renaming, etc.

Issue 160 - Break up dialog components

---

src/ProjectControl.tsx
src/Projects.tsx

Issue 164: add new properties to define project type

---

.eslintrc.yml
src/Financing.tsx
src/ProjectControl.tsx
src/Projects.tsx
src/components/Dialogs/CompareDialog.tsx
src/components/Dialogs/InfoDialog.tsx
src/components/Dialogs/ProjectDialog.tsx
src/components/Dialogs/ProjectInfoCard.tsx
src/components/Dialogs/dialog-functions-and-types.tsx
src/functions-and-types.tsx

Issue 142 - Add financing options to project info dialog and compare dialogs 

---

src/PageControls.tsx
src/Pages.tsx
src/ProjectControl.tsx
src/Projects.tsx

Issue 119: LCFFS - Add Low carbon fuels, feedstocks and Energy sources

---

src/App.tsx
src/Financing.tsx
src/ProjectControl.tsx
src/components/CurrentPage.tsx
src/components/Dashboard.tsx
src/components/Dialogs/ProjectInfoCard.tsx
src/components/SelectGameSettings.tsx
src/components/YearRecap.tsx

170 - Add choose financing options at game settings

---

.github/workflows/main.yml
.github/workflows/web.yml

- Updates runner labels to `dev` and `prod` for web server runners
- Adds a job to deploy web builds to dev web server if the branch == `develop`

Updated workflow conf - added dev deploy, updated runner labels

---

src/App.tsx

Issue 138: Scroll Jumping when loading Year Recap

---

src/PageControls.tsx

Issue 19 : Return Fuel Switching Projects

---

src/App.tsx
src/Financing.tsx
src/ProjectControl.tsx
src/Projects.tsx
src/components/CurrentPage.tsx
src/components/Dashboard.tsx
src/components/Dialogs/ProjectInfoCard.tsx
src/components/GroupedChoices.tsx
src/components/SelectGameSettings.tsx
src/components/YearRecap.tsx
src/functions-and-types.tsx

#143
Add logic and mechanics for financing option, regular projects, and renewables

Issue 143 - Add implementation logic with financing options

---

src/components/YearRecap.tsx
src/components/YearRecapCharts.tsx

Issue 167 - Make year recap charts responsive

---

src/App.tsx
src/components/Dialogs/InfoDialog.tsx

Issue 187 - Remove unused info cards

---

src/App.scss
src/Financing.tsx
src/Projects.tsx
src/components/GaugeChart.tsx
src/components/YearRecap.tsx
src/functions-and-types.tsx

Issue 172 - Add Financing info to year recap projects, tighten up styles

---

package.json
src/ProjectControl.tsx

Issue 191 - Budget bar bug

---

GAMEPLAY.md
src/App.tsx
src/Financing.tsx
src/ProjectControl.tsx
src/components/YearRecap.tsx

#147 #197
I think I incorrectly copied part of the onclick function from the other button - removed. Also fixing the wrong payoff year condition

Issue 147-197 Add gameplay readme, fix bugs related to unimplementing renewable

---

GAMEPLAY.md
src/App.tsx
src/Financing.tsx
src/ProjectControl.tsx
src/components/Dialogs/CompareDialog.tsx
src/components/Dialogs/ProjectDialog.tsx
src/components/Dialogs/ProjectInfoCard.tsx
src/components/SelectGameSettings.tsx
src/components/YearRecap.tsx

#122 
Genereal financing fixes:
Make sure year end net costs get calculated from 'completed' projects when financed
Handle financing start year
Display when project is paid in full (for renewables and capital funding)

Issue 122 - General financing fixes from testing

---

GAMEPLAY.md
src/App.tsx
src/Financing.tsx
src/ProjectControl.tsx
src/components/Dashboard.tsx
src/components/Dialogs/InfoDialog.tsx
src/components/YearRecap.tsx

#200 #201 #203 
Related changes for capital fundings state, general warnings, backward year bug fixes

Issue 200, 201, 203 - Various Capital Funding, warnings, bugs

---

src/App.tsx
src/ProjectControl.tsx
src/components/SelectGameSettings.tsx

Issue 209 - Add godmode in develop

---

src/App.tsx
src/components/SelectGameSettings.tsx

Issue 209 godmode fixes

---

src/components/Dashboard.tsx
src/trackedStats.tsx

Issue 186 - Add yearly emissions factors for electricity

---

src/components/Dashboard.tsx

Issue 193 quick fix to Nat Gas unit in chart

---

src/App.scss
src/App.tsx
src/components/Dashboard.tsx
src/components/SelectGameSettings.tsx
src/trackedStats.tsx

issue 213: new game settings added

---

src/Financing.tsx
src/ProjectControl.tsx
src/Projects.tsx

Issue 214 NV - Change PPPA related language

---

src/Projects.tsx

Issues 230 & 224

---

src/App.tsx
src/ProjectControl.tsx
src/components/YearRecap.tsx

Removing some noise, making clearer what numbers are for

cleanup console logs

---

src/App.tsx

Landfill gas defaults to 0

---

src/App.tsx
src/Financing.tsx
src/components/YearRecap.tsx

Fixes capital funding when traveling back a year, also mistakenly commented out code in year recap

Fix prev year capita funding state

---

.env.development
.env.production
.github/workflows/web.yml
package-lock.json
package.json
public/index.html
src/App.tsx
src/Financing.tsx
src/components/SelectGameSettings.tsx

Issue 240 - Use Env files to differentiate dev/prod deploy

---

src/App.tsx
src/Financing.tsx
src/ProjectControl.tsx
src/Projects.tsx

#248 
Also adding more logging to setup new year

Issue 248 - Project cost updates, add isPPA flag and apply costs every year

---

src/ProjectControl.tsx

Issue 252 - Implement limits for financed projects

---

src/App.tsx

Issue 255: Make game harder - only 1/2 energy savings

---

src/Projects.tsx

Issue 256: Implement +/- energy savings surprises

---

src/Projects.tsx
src/components/YearRecap.tsx

Use title and text of surprise for card. Use project name as subheader

Use title and text of surprise

---

package-lock.json
package.json
src/Financing.tsx
src/components/SelectGameSettings.tsx

#265 
Fixed - was using the wrong property + bad math

Issue 265 - Obey loan terms in 2 year

---

src/components/SelectGameSettings.tsx
src/trackedStats.tsx

Issue 266 - Fix end game year in electricity emissions factors obvject

---

src/components/YearRecapCharts.tsx

Issue 253: EoY graphs

---

src/PageControls.tsx

Issue 270 - Make EOG report viewable at lose page

---

GAMEPLAY.md
src/App.tsx
src/ProjectControl.tsx
src/Projects.tsx
src/components/YearRecap.tsx

Issue 237 - Yearly cost savings on selected renewed projects

---

src/components/EndGameReport/EndGameReportPage.tsx
src/components/EnergyUseLineChart.tsx

Issues 123 & 180

---

src/Projects.tsx

Issue 115: Quick fixes to projects

---

src/App.tsx
src/Projects.tsx

Issue 278: Increase NG starting value (1 year) to 150000MMBtu

---

src/components/YearRecap.tsx

Issue 285 - changing year recap messaging

---

GAMEPLAY.md
src/App.tsx
src/components/EndGameReport/EndGameReportPage.tsx
src/components/EnergyUseLineChart.tsx
src/trackedStats.tsx

Issue 180 - Revert display wording changes, fix current game year snafu

---

src/App.tsx
src/Projects.tsx

#275 
- Multiplier was applied incorrectly
- Change solar thermal to never

Change solar thermal to always, fix multiplier placemet

---

src/App.tsx
src/components/YearRecap.tsx

Issue 275 c - More carryover related fixes - 298/296

---

src/components/EndGameReport/EndGameReportPage.tsx
src/components/YearRecap.tsx

Updates a couple of places where the newer getImplementationCost() should be called instead of previous logic
Also removes an unused YearRecap method.

Fix yearRecap netCost

---

src/components/Dashboard.tsx
src/components/HeaderFinances.tsx
src/components/HorizontalBar.tsx

#284 
change Dashboard.tsx to functional component
add floating header with finances
add finances available text

Issue 284 - Add floating header to gameplay page. Add finances available text

---

src/components/YearRecap.tsx

Issue 294 header sticky EoY

---

src/Financing.tsx
src/components/YearRecap.tsx

Hotfix projected financing

---

src/Financing.tsx
src/Projects.tsx

Issues 299 306 309

---

src/App.scss
src/App.tsx
src/components/WinGame.tsx

Add in animations and cleanup transitions

---

src/App.tsx

2 year interval now default

---

src/Projects.tsx

project tweaks

---

src/App.scss
src/App.tsx
src/components/WinGame.tsx
src/trackedStats.tsx

Issue 279 - Rewrite stats, readability changes, add kg per year

---

src/App.scss
src/App.tsx
src/components/Dialogs/EndGameDialog.tsx
src/components/LoseGame.tsx
src/components/WinGame.tsx

Final changes to loseGame, styling, stat changes

---

src/App.tsx
src/components/WinGame.tsx
src/trackedStats.tsx

Issue 279 - Use carbon savings per tonne stat

---

src/components/LoseGame.tsx

Adjust losing text size

---

src/PageControls.tsx
src/components/StartPage.tsx

Issue 359: removed no no words from start page and intro

---

.env.development
.env.production

369 Change url for ir-utilities
